### DISCUSSION TITLE
Inverter randomly starting to charge battery

### DISCUSSION THREAD

**Discussion by onetoomany** [cmcgerty/Sofar2mqtt#74] [General]
I'm running my Sofar from Home Assistant. I've really got two modes that I'm using:
1. Force charge the battery, as Octopus is cheap
2. Run normally off the batteries / solar as Octopus is expensive

I'm seeing this run well, but every now and then the inverter decides to switch into charge mode. No instructions have been sent from Home Assistant to force it to do this.

I had it do this at 18:45 yesterday and 10.51 today. This is not ideal, as I ended up charging at 40p rather than consuming what I bought at 23p.

```
  - alias: Set inverter to Charge
    service: mqtt.publish
    data:
      qos: "1"
      retain: true
      topic: Sofar2mqtt/set/charge
      payload: "3000"

```
```
  - alias: Set inverter to Auto
    service: mqtt.publish
    data:
      qos: "1"
      retain: true
      topic: Sofar2mqtt/set/auto
      payload: "true"
```

I don't seem to have any entity that tells me what mode the inverter is running in. I had thought it would be Sofar2mqtt/state, but this is just 0-Standby and 2-Charging even when the inverter is discharging.
